URDF_PATH: /home/ilv/ros2_ws/eRob_moveit/src/eRob_ROS2_MoveIt/zeroerr/config/paint/erob_arm_small.urdf
SRDF_PATH: /home/ilv/ros2_ws/eRob_moveit/src/eRob_ROS2_MoveIt/zeroerr/config/paint/eRobo3.srdf
COLLISION_TIP_LINK: tool0
DEFAULT_WORKOBJECT:
- 0
- 0
- 0
- 0
- 0
- 16.2


# Painting: disable collision checking (tool contacts workpiece)
ENABLE_COLLISION_CHECKING: false
