default_velocity_scaling_factor: 0.25
default_acceleration_scaling_factor: 0.5

joint_limits:
  Joint_1:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 8.0
    has_acceleration_limits: true
    max_acceleration: 6.0
    max_deceleration: -6.0
    has_jerk_limits: true
    max_jerk: 60.0

  Joint_2:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 8.0
    has_acceleration_limits: true
    max_acceleration: 6.0
    max_deceleration: -6.0
    has_jerk_limits: true
    max_jerk: 60.0

  Joint_3:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 8.0
    has_acceleration_limits: true
    max_acceleration: 6.0
    max_deceleration: -6.0
    has_jerk_limits: true
    max_jerk: 60.0

  Joint_4:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 8.0
    max_deceleration: -8.0
    has_jerk_limits: true
    max_jerk: 80.0

  Joint_5:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 8.0
    max_deceleration: -8.0
    has_jerk_limits: true
    max_jerk: 80.0

  Joint_6:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    max_deceleration: -10.0
    has_jerk_limits: true
    max_jerk: 100.0