# Fairino launcher config

ROBOT_TYPE=fairino
BUILD_WORKSPACE=0
USE_RVIZ=false

WORKSPACE_DIR="${SCRIPT_DIR}"
ROS_SETUP_FILE="${ROS_SETUP_FILE:-${DEFAULT_ROS_SETUP_FILE}}"
BASE_UNDERLAY_SETUP_FILE="${ROOT_WS_DIR}/install/local_setup.bash"
WORKSPACE_SETUP_FILE="${SCRIPT_DIR}/install/local_setup.bash"

FAIRINO_PACKAGE=fairino5_v6_moveit2_config
FAIRINO_LAUNCH_FILE=demo.launch.py

# Set to 1 to launch PlotJuggler instead of the motion oscilloscope
FAIRINO_PLOTJUGGLER=0
